name = "dynotic-uploader"
account_id = "5b66e179d873e88287a27ac22ab66678"
workers_dev = true
compatibility_date = "2026-02-27"
main = "worker.js"

[[r2_buckets]]
binding = "dynotic-storage"
bucket_name = "dynotic-storage"
